In [18]:
import pandas as pd
import numpy as np
from scipy import stats 
from scipy.stats import norm

In [ ]:
#Hypothesis testing -cutletfile -using Two sample ttest

In [19]:
cutl=pd.read_csv("Cutlets.csv")
cutl

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [20]:
#Two sample t test
stats.ttest_ind(data.iloc[0:35,0:1],data.iloc[0:35,1:2])

Ttest_indResult(statistic=array([0.72286887]), pvalue=array([0.47223947]))

In [ ]:
#using p value we are deciding to accept or reject null hypothesis.
#Here p values greater  than significance  level(5%) so we ACCEPT NULL HYPOTHESIS.

In [ ]:
#The end 

In [ ]:
#**************************************************************************************************************

In [ ]:
#***************************************************************************************************************

In [ ]:
#Hypothesis testing -LabTATfile -using Anova test

In [21]:
LabT=pd.read_csv("LabTAT.csv")
LabT

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [23]:
#Anova test and f statistics
stats.f_oneway(LabT.iloc[:,0],LabT.iloc[:,1],LabT.iloc[:,2],LabT.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
#using p value we are deciding to accept or reject null hypothesis.
#Here p values less  than significance  level(5%) so we ACCEPT ALTERNATE HYPOTHESIS.

In [ ]:
#TheEnd

In [ ]:
#******************************************************************************************************************************

In [ ]:
#******************************************************************************************************************************

In [ ]:
#Hypothesis testing Buyer ratio - using Chi Square test because we have more than two proportions

In [24]:
BR=pd.read_csv("BuyerRatio.csv")
BR

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [25]:
obsval=np.array([[50,142,131,70],[435,1523,1356,750]])
obsval

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [26]:
#Chi Square test
stats.chi2_contingency(obsval)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [ ]:
#we got p value as 0.66 which is greater than significance level.
#so we are going to ACCEPT NULL HYPOTHESIS

In [ ]:
#The End

In [ ]:
#*******************************************************************************************************************************

In [ ]:
#*******************************************************************************************************************************

In [ ]:
#Hypothesis  testing- Customer order form- using chi square test

In [27]:
cof=pd.read_csv("Costomer+OrderForm.csv")
cof

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [28]:
cof.Phillippines.value_counts()   

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [29]:
cof.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [30]:
cof.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [31]:
cof.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [32]:
cof1=np.array([[271,267,269,280],[29,33,31,20]])
cof1

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [33]:
#Chi square test
stats.chi2_contingency(cof1)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [ ]:
#we got p value as 0.277 which is greater than significance level.
#so we are going to ACCEPT NULL HYPOTHESIS

In [ ]:
#The Final End

In [ ]:
#---------------------------------------------------------------------------------------------------------------------------

In [ ]:
#---------------------------------------------------------------------------------------------------------------------------